import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  await prisma.project_genre.createMany({
    data: [
      { genre_name: 'Fantasy' },
      { genre_name: 'Science Fiction' },
      { genre_name: 'Mystery' },
      { genre_name: 'Thriller' },
      { genre_name: 'Romance' },
      { genre_name: 'Horror' },
      { genre_name: 'Historical Fiction' },
      { genre_name: 'Adventure' },
      { genre_name: 'Young Adult' },
      { genre_name: 'Dystopia' },
      { genre_name: 'Crime Fiction' },
      { genre_name: 'Comedy' },
      { genre_name: 'Humor' },
      { genre_name: 'Drama' },
      { genre_name: 'Documentary' },
      { genre_name: 'Biyography' },
      { genre_name: 'War' },
      { genre_name: 'Family' },
      { genre_name: 'Epic' },
      { genre_name: 'Rom-Com' },
      { genre_name: 'Superhero' }
    ],
    skipDuplicates: true
  })

  await prisma.project_tag.createMany({
    data: [
      { tag_name: 'abuse' },
      { tag_name: 'academia' },
      { tag_name: 'accounting' },
      { tag_name: 'action' },
      { tag_name: 'activism' },
      { tag_name: 'adaptations' },
      { tag_name: 'adolescence' },
      { tag_name: 'adoption' },
      { tag_name: 'adult' },
      { tag_name: 'adventure' },
      { tag_name: 'agriculture' },
      { tag_name: 'alcohol' },
      { tag_name: 'algebra' },
      { tag_name: 'aliens' },
      { tag_name: 'alternate-history' },
      { tag_name: 'alternate-universe' },
      { tag_name: 'america' },
      { tag_name: 'animals' },
      { tag_name: 'anthropology' },
      { tag_name: 'antiquities' },
      { tag_name: 'antisemitism' },
      { tag_name: 'apocalyptic' },
      { tag_name: 'architecture' },
      { tag_name: 'art' },
      { tag_name: 'art-history' },
      { tag_name: 'artificial-intelligence' },
      { tag_name: 'asia' },
      { tag_name: 'astrology' },
      { tag_name: 'astronomy' },
      { tag_name: 'atheism' },
      { tag_name: 'autobiography' },
      { tag_name: 'belief' },
      { tag_name: 'biography' },
      { tag_name: 'business' },
      { tag_name: 'cars' },
      { tag_name: 'cartoon' },
      { tag_name: 'cats' },
      { tag_name: 'chemistry' },
      { tag_name: 'chess' },
      { tag_name: 'chick-lit' },
      { tag_name: 'childrens' },
      { tag_name: 'cities' },
      { tag_name: 'classical-music' },
      { tag_name: 'climate-change' },
      { tag_name: 'climbing' },
      { tag_name: 'coding' },
      { tag_name: 'college' },
      { tag_name: 'comedy' },
      { tag_name: 'comic-book' },
      { tag_name: 'comics' },
      { tag_name: 'communication' },
      { tag_name: 'computers' },
      { tag_name: 'conflict-of-interest' },
      { tag_name: 'conspiracy-theories' },
      { tag_name: 'construction' },
      { tag_name: 'counter-culture' },
      { tag_name: 'counting' },
      { tag_name: 'crafts' },
      { tag_name: 'crime' },
      { tag_name: 'criticism' },
      { tag_name: 'cuisine' },
      { tag_name: 'culinary' },
      { tag_name: 'cultural' },
      { tag_name: 'cultural-heritage' },
      { tag_name: 'cyberpunk' },
      { tag_name: 'dark-fantasy' },
      { tag_name: 'death' },
      { tag_name: 'deception' },
      { tag_name: 'demons' },
      { tag_name: 'design' },
      { tag_name: 'detective' },
      { tag_name: 'diary' },
      { tag_name: 'dictionaries' },
      { tag_name: 'dinosaurs' },
      { tag_name: 'disease' },
      { tag_name: 'distrust' },
      { tag_name: 'divorce' },
      { tag_name: 'dogs' },
      { tag_name: 'dragons' },
      { tag_name: 'drama' },
      { tag_name: 'drawing' },
      { tag_name: 'dystopia' },
      { tag_name: 'ecology' },
      { tag_name: 'economics' },
      { tag_name: 'education' },
      { tag_name: 'emotion' },
      { tag_name: 'engineering' },
      { tag_name: 'environment' },
      { tag_name: 'erotica' },
      { tag_name: 'espionage' },
      { tag_name: 'ethnic' },
      { tag_name: 'ethnography' },
      { tag_name: 'european-history' },
      { tag_name: 'evolution' },
      { tag_name: 'fairy-tales' },
      { tag_name: 'faith' },
      { tag_name: 'family' },
      { tag_name: 'fantasy' },
      { tag_name: 'fashion' },
      { tag_name: 'feminism' },
      { tag_name: 'fiction' },
      { tag_name: 'film' },
      { tag_name: 'finance' },
      { tag_name: 'folk-tales' },
      { tag_name: 'folklore' },
      { tag_name: 'food' },
      { tag_name: 'football' },
      { tag_name: 'futurism' },
      { tag_name: 'games' },
      { tag_name: 'gastronomy' },
      { tag_name: 'gender' },
      { tag_name: 'geography' },
      { tag_name: 'geology' },
      { tag_name: 'geometry' },
      { tag_name: 'ghosts' },
      { tag_name: 'global-warming' },
      { tag_name: 'god' },
      { tag_name: 'gothic' },
      { tag_name: 'greek-mythology' },
      { tag_name: 'health' },
      { tag_name: 'hierarchy' },
      { tag_name: 'history' },
      { tag_name: 'holocaust' },
      { tag_name: 'horror' },
      { tag_name: 'humor' },
      { tag_name: 'illness' },
      { tag_name: 'journalism' },
      { tag_name: 'labor' },
      { tag_name: 'language' },
      { tag_name: 'lgbt' },
      { tag_name: 'linguistics' },
      { tag_name: 'love' },
      { tag_name: 'magic' },
      { tag_name: 'magical-realism' },
      { tag_name: 'management' },
      { tag_name: 'medical' },
      { tag_name: 'medieval' },
      { tag_name: 'memoir' },
      { tag_name: 'mental-illness' },
      { tag_name: 'mermaids' },
      { tag_name: 'money' },
      { tag_name: 'monsters' },
      { tag_name: 'murder' },
      { tag_name: 'music' },
      { tag_name: 'musicals' },
      { tag_name: 'mystery' },
      { tag_name: 'mysticism' },
      { tag_name: 'mythology' },
      { tag_name: 'nature' },
      { tag_name: 'near-future' },
      { tag_name: 'noir' },
      { tag_name: 'non-fiction' },
      { tag_name: 'occult' },
      { tag_name: 'oral-history' },
      { tag_name: 'paranormal' },
      { tag_name: 'parenting' },
      { tag_name: 'philosophy' },
      { tag_name: 'photography' },
      { tag_name: 'pirates' },
      { tag_name: 'plants' },
      { tag_name: 'poetry' },
      { tag_name: 'police' },
      { tag_name: 'politics' },
      { tag_name: 'polygamy' },
      { tag_name: 'pop-culture' },
      { tag_name: 'popular-science' },
      { tag_name: 'pornography' },
      { tag_name: 'post-apocalyptic' },
      { tag_name: 'prehistory' },
      { tag_name: 'princesses' },
      { tag_name: 'prostitution' },
      { tag_name: 'psychiatry' },
      { tag_name: 'psychoanalysis' },
      { tag_name: 'psychological-thriller' },
      { tag_name: 'psychology' },
      { tag_name: 'punk' },
      { tag_name: 'race' },
      { tag_name: 'relationships' },
      { tag_name: 'religion' },
      { tag_name: 'school' },
      { tag_name: 'science' },
      { tag_name: 'science-fiction' },
      { tag_name: 'scripture' },
      { tag_name: 'sexuality' },
      { tag_name: 'short-stories' },
      { tag_name: 'social' },
      { tag_name: 'social-change' },
      { tag_name: 'social-issues' },
      { tag_name: 'social-justice' },
      { tag_name: 'social-media' },
      { tag_name: 'social-movements' },
      { tag_name: 'society' },
      { tag_name: 'sociology' },
      { tag_name: 'soldiers' },
      { tag_name: 'space' },
      { tag_name: 'students' },
      { tag_name: 'supernatural' },
      { tag_name: 'teachers' },
      { tag_name: 'teaching' },
      { tag_name: 'technology' },
      { tag_name: 'teen' },
      { tag_name: 'terrorism' },
      { tag_name: 'thriller' },
      { tag_name: 'time-travel' },
      { tag_name: 'tragedy' },
      { tag_name: 'travel' },
      { tag_name: 'utopia' },
      { tag_name: 'vampires' },
      { tag_name: 'vegan' },
      { tag_name: 'vegetarian' },
      { tag_name: 'virtual-reality' },
      { tag_name: 'visual-art' },
      { tag_name: 'werewolves' },
      { tag_name: 'witchcraft' },
      { tag_name: 'witches' },
      { tag_name: 'wizards' },
      { tag_name: 'wolves' },
      { tag_name: 'womens' },
      { tag_name: 'womens-rights' },
      { tag_name: 'womens-studies' },
      { tag_name: 'world-history' },
      { tag_name: 'world-war-i' },
      { tag_name: 'world-war-ii' },
      { tag_name: 'young-adult' },
      { tag_name: 'zombies' },
      { tag_name: 'turkey' },
      { tag_name: 'turkey-history' }
    ],
    skipDuplicates: true
  })
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
